In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
dataset = pd.read_csv('/content/movies.csv')

In [ ]:
dataset.isnull().sum()

index                      0
budget                     0
genres                    28
homepage                3091
id                         0
keywords                 412
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
cast                      43
crew                       0
director                  30
dtype: int64

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   index                 4803 non-null   int64
 1   budget                4803 non-null   int64
 2   genres                4775 non-null   object
 3   homepage              1712 non-null   object
 4   id                    4803 non-null   int64
 5   keywords              4391 non-null   object
 6   original_language     4803 non-null   object
 7   original_title        4803 non-null   object
 8   overview              4800 non-null   object
 9   popularity            4803 non-null   float64
 10  production_companies  4803 non-null   object
 11  production_countries  4803 non-null   object
 12  release_date          4802 non-null   object
 13  revenue               4803 non-null   int64
 14  runtime               4801 non-null   float64
 15  spoken_languages      4803 non-null   object
 16  status                4803 non-null   object
 17  tagline               3959 non-null   object
 18  title                 4803 non-null   object
 19  vote_average          4803 non-null   float64
 20  vote_count            4803 non-null   int64
 21  cast                  4760 non-null   object
 22  crew                  4803 non-null   object
 23  director              4773 non-null   object
dtypes: float64(3), int64(5), object(16)
memory usage: 900.7+ KB

In [ ]:
dataset.select_dtypes(include='float64').columns

Index(['popularity', 'runtime', 'vote_average'], dtype='object')

In [ ]:
from sklearn.impute import SimpleImputer

In [ ]:
si=SimpleImputer(strategy='mean')
ar=si.fit_transform(dataset[['popularity', 'runtime', 'vote_average']])

In [ ]:
new_dataset=pd.DataFrame(ar,columns=dataset.select_dtypes(include='float64').columns)

In [ ]:
new_dataset.isnull().sum()

popularity      0
runtime         0
vote_average    0
dtype: int64

In [ ]:
new_dataset

      popularity  runtime  vote_average
0     150.437577    162.0           7.2
1     139.082615    169.0           6.9
2     107.376788    148.0           6.3
3     112.312950    165.0           7.6
4      43.926995    132.0           6.1
...          ...      ...           ...
4798   14.269792     81.0           6.6
4799    0.642552     85.0           5.9
4800    1.444476    120.0           7.0
4801    0.857008     98.0           5.7
4802    1.929883     90.0           6.3

[4803 rows x 3 columns]

In [ ]:
dataset['runtime'].mean()

106.87585919600083